apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # On pointe vers tes manifests techniques réorganisés
  - ../../../clusters-config/01-prerequisites/
  - ../../../clusters-config/02-operators/
