apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# On liste ici les dossiers contenant tes ressources techniques
resources:
  - 01-prerequisites/
  - 02-operators/

# Optionnel : Tu peux forcer des labels communs à toute la stack RHOSO ici
commonLabels:
  app.kubernetes.io/part-of: rhoso-bundle
  managed-by: argocd
