---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-rhoso-demo-env-controlplane
  namespace: openshift-gitops
  annotations:
    # Cette application se synchronise APRES installation des operateurs (wave -10)
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/abakabir/abk-rhoso-gitops.git
    targetRevision: HEAD
    path: 03-config/environments/demo-env/controlplane/
  destination:
    server: https://kubernetes.default.svc
    # Le Control Plane est déployé dans le namespace 'openstack'
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Option vitale pour permettre à Kustomize de gérer les CRDs non encore présentes
      - SkipDryRunOnMissingResource=true
