---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-prerequisites
  namespace: openshift-gitops
  annotations:
    # On garde une wave très basse pour l'application elle-même
    argocd.argoproj.io/sync-wave: "-40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/abakabir/abk-rhoso-gitops.git
    targetRevision: HEAD
    path: 01-prerequisites
  kustomize:
      loadRestrictor: none
  destination:
    server: https://kubernetes.default.svc
    # Les ressources seront créées dans leurs namespaces respectifs 
    # définis dans les sous-dossiers (metallb-system, openshift-nmstate, etc.)
    namespace: openshift-gitops 
  syncPolicy:
    automated:
      prune: true      # Supprime les ressources si tu les enlèves du Git
      selfHeal: true   # Répare si quelqu'un modifie manuellement le cluster
    syncOptions:
      - CreateNamespace=true # Crée le namespace de destination s'il manque
