---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openstack-operator

patches: 
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1managed-by
        value: "openshift-gitops"
 

