---
# 01-prerequisites/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nmstate-operator
  - metallb-operator
  - namespace-openstack.yaml

# On "active" les annotations via le composant
components:
  - ../shared/annotations
